### ISSUE TITLE
Question: How to add in my slack?

### ISSUE THREAD

**Issue by vishalpatel1327** [mroth/slacknimate#6]
I download   it and genrate tocken also 

but i cant found the way , how to use zip flib file for slack can u plz guide me?

**Comment by mroth** [comment]
Download the appropriate file for your platform (Windows, Mac, Unix), unzip, and run on the command line. The examples in the README show the syntax.

**Comment by vishalpatel1327** [comment]
but it return 
slacknimate: command not found
  plz plz  can u plz describe how can i install "slacknimate"  in ubantu 16.04

**Comment by vishalpatel1327** [comment]
yes yess got success   grt thing  hahaha tq so much   u  r awsome
