### ISSUE TITLE
Clarify requirement for as_user: true

### ISSUE THREAD

**Issue by patcon** [mroth/slacknimate#7]
Hi there! Thanks for this app! I'm thinking on how to put it to use :)

I came across [the note as the bottom of the README](https://github.com/mroth/slacknimate#bots):

> In order for Slack message editing to work, the message must be posted as_user: true, which will show as coming from whomever owns the token. This is due to how the security model for Slack message editing works.
>
> For bots, you must create a new bot in the team settings and substitute in the auth token for that bot.

**How does this manifest in your experience?** I contribute to an app that does edits and has `as_user: false`, and I don't think we've noticed the edge-case you're referring to, so I'm particularly curious to understand!

Does this relate to this section of official docs? https://api.slack.com/methods/chat.postMessage#authorship

**Comment by patcon** [comment]
Also, re: @mroth profile

> Artist + hacker. **Focused on building decentralized orgs, humane tech.**

❤️

I'm aspiring to do the same thing with chatops + grassroots organizing + civic tech :)

**Comment by mroth** [comment]
Thanks @patcon! This is interesting. It seems likely that the permissions for the Slack have evolved since this was written.  At the time, only user messages were editable after posting. Let me know if you can get this working with bot messages, and I'll remove that from the README!

**Comment by patcon** [comment]
Sounds good. This tool is in my back pocket for later, so it might not be me who investigates (at least not now). Feel free to close if you'd prefer this not linger!

**Comment by mroth** [comment]
This is now addressed in v1.1. Much has changed about Slack tokens!
